services:
  - type: web
    name: buddy-script-be
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
